---
kind: pipeline
type: docker
name: default

steps:
  - name: build-frontend
    image: node:10
    when:
      event: push
    environment:
      LANG: C.UTF-8
    commands:
      - yarn
      - yarn lint
      - yarn build

  - name: missing-migrations
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      LANG: C.UTF-8
      DATABASE: database
    commands:
      - make ci_settings
      - tox -e missing-migrations

  - name: tests
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      LANG: C.UTF-8
      DATABASE: database
    commands:
      - tox -e tests

  - name: isort
    image: abakus/lego-testbase
    when:
      event: push
    environment:
      LANG: C.UTF-8
    commands:
      - tox -e isort

  - name: black
    image: abakus/lego-testbase
    pull: true
    when:
      event: push
    environment:
      LANG: C.UTF-8
    commands:
      - tox -e black

  - name: coverage
    image: abakus/lego-testbase
    when:
      event: push
    depends_on:
      - tests
    environment:
      LANG: C.UTF-8
      DATABASE: database
    commands:
      - tox -e coverage

  - name: docker
    image: plugins/docker
    when:
      branch:
        - prod
      status: success
      event: push
    depends_on:
      - build-frontend
      - missing-migrations
      - tests
      - isort
      - black
      - coverage
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/committee-admissions
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - version-${DRONE_COMMIT_SHA:0:7}
      build_args:
        RELEASE: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy
    image: abakus/ansible-deploy
    depends_on:
      - docker
    when:
      branch:
        - prod
      event: push
      status: success
    settings:
      playbook: /infrastructure/esas/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - admissions
      limit: esas
      extra_vars: admissions_version=version-${DRONE_COMMIT_SHA:0:7}
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key

services:
  - name: database
    image: postgres:9.5
    environment:
      POSTGRES_USER: admissions
      POSTGRES_HOST_AUTH_METHOD: trust
